### ISSUE TITLE
Future plan comment re: optimisation with xor

### ISSUE THREAD

**Issue by tegerdine** [skx/cpm-fat#24]
Hi skx, 
Just to potentially save you some future debug effort, your comment in README.md:
> "Obvious easy-win is replacing instructions such as ld b,0 with xor b."

won't work - "xor b" means "xor a,b". The "xor a" trick only works on a.
Cheers!

**Comment by skx** [comment]
Thanks for the comment, you're entirely correct.

(Sorry for the belated reply I somehow had no notification of this _issue_ !)
